### ISSUE TITLE
Need Modified Skin for Krypton

### ISSUE THREAD

**Issue by MarkCallow** [pkscout/repository.beta.pkscout#2]
Will you be providing modified Estuary/Estouch skins for Krypton? Or preferably will you make Artist Slideshow support a standard part of these skins?

Or are we going to have to stick with a modified Confluence to have Artist Slideshow support?

**Comment by pkscout** [comment]
The Kodi team has declined to make AS support a standard part of the skin.  Once Krypton gets to RC candidates I will either provide files so you can update the skin or a fully modded skin like I did for Confluence.

**Comment by MarkCallow** [comment]
That's too bad. I suppose they have their reasons.

Please reopen this issue and only close it when you provide files or an updated skin for Krypton. That way, I don't have to keep checking your repos to see if anything is available yet.

When you do, please consider my [issue #1 ](https://github.com/pkscout/skin.confluence.jarvis.pkscout.mod/issues/1) in your skin.confluence.jarvis.pkscout.mod repo.

**Comment by pkscout** [comment]
New Estuary mod for AS support has now been released and is in my skin repo.  At this point I understand your other issue, but it will be too much work to change what I've done.

**Comment by MarkCallow** [comment]
I am struggling with this:

- There are no instructions for how to use the mod'ed skin. I want to put it under my userdata so don't have to keep restoring the mods after Kodi updates.
- https://github.com/pkscout/skin.estuary.krypton.pkscout.mod is not a fork of the upstream estuary repo so there is no easy way to determine what you have actually changed.

Re issue #1, I can see that creating a repo with branches for all of the Confluence mods for previous versions of Kodi would be a lot of work. However going forward putting mods of Estuary for future Kodi releases into different branches of https://github.com/pkscout/skin.estuary.krypton.pkscout.mod seems like less work than making a new repo each time.

**Comment by pkscout** [comment]
Please see:

http://forum.kodi.tv/showthread.php?tid=303946

For information on installing and using this skin mod.  If you're trying to install this directly from this GitHub site you are making your life way to hard.

This is not a fork of the upstream Estuary because that is sometimes ahead of the actual shipping versions.  I keep this in sync with what's shipped with Kodi releases.

I won't be doing this mod as branches because whenever a new major version of Kodi comes out I start with that skin as the baseline.  So it's easier for me to just start another GitHub repo when I do that.  And if you follow the directions above to install the skin, then when I release a new version of the skin mod for the matching version of Kodi you can easily install it.

**Comment by MarkCallow** [comment]
I installed the modified skin. A few points:
1. The link you referenced does not have installation instructions, only a note that you need the zip file with the modified skin. It took quite a bit of intuition to finally get it working.
2. Installing from GitHub is not "way too hard". With the exception of installing `git` if you don't already have it, the steps are pretty much the same:
    1. Find and navigate to the Kodi's special://home/add-ons directory; `git clone` the repo. (GitHub way). Or download the provided zipfile; navigate the Kodi GUI to find the Add-Ons "Install from Zip file" button, click it; navigate to and select the downloaded zip file. (Your recommended way)
    2. Navigate the Kodi GUI to find the newly installed skin in Add-Ons and enable it.
    3. Navigate the Kodi GUI to Settings->Interface Settings->Skin and select the modified skin.
    4. Navigate the Kodi GUI to Settings->Skin Settings and re-set the options you had set in the unmodified skin and any new options you want.

The last 3 steps are the same in either case. ii & iii are where intuition was needed. Finding the "Install from Zip file" button was more difficult than finding special://home.

Now that I have this set up, all I have to do when you update the modified skin is `git pull`.
